[package]
name = "prage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Rust Samurai <chatgpt@openai.com>"]
description = "ğŸ” Password-based file encryption using age"
readme = "README.md"
repository = "https://github.com/starmoonsky/prage"

[dependencies]
age       = "0.11"
clap      = { version = "4.3.1", features = ["derive"] }
rpassword = "7.4.0"
anyhow    = "1.0.98"
